### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by Sugoiiiii** [shiyingqi/luac-Decryption#4]
C:\Users\M\Desktop\luac-Decryption-master>python main.py -d bsj!@#cocos XXTEA C:\Users\Min\Desktop\game\assets\scr
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import xxtea
ModuleNotFoundError: No module named 'xxtea'

![image](https://user-images.githubusercontent.com/93562135/167154924-93fcf762-5ca9-4edd-bec0-7a4cb3c66c7b.png)

**Comment by Mas0nShi** [comment]
> ModuleNotFoundError: No module named 'xxtea'

hello, you need install module `xxtea` first.
```shell
pip3 install xxtea
```

**Comment by Sugoiiiii** [comment]
ya i am done intall xxtea and loguru 

C:\Users\M\Desktop\luac-Decryption-master>python main.py -d bsj!@#cocos XXTEA C:\Users\Min\Desktop\game\assets\scr

This is decrypt for Coco2d-luac .luac.
←[1;37m Usage :  ←[0m
        python main.py [-d] [xxteaKey] [sign] [jscDir/zipFile]
←[1;37m Example :  ←[0m
        python main.py -d e73c83539f2e65ab159 b4d6f1b968 C:\DecJsc-master\src
        python main.py -d e73c83539f2e65ab159 b4d6f1b968 C:\DecJsc-master\game.zip
←[1;37m Tips :  ←[0m
        -d or -decrypt [decrypt]
        If the TEA is 16 bytes of \x00, please fill in NONE
        Supports folders and individual LUAC or ZIP files
        If you have any questions, please contact [ MasonShi@88.com ]

**Comment by Mas0nShi** [comment]
try use quote include params.
e.g. 
```shell
python main.py -d "e73c83539f2e65ab159" "b4d6f1b968" "C:\DecJsc-master\src"
```

**Comment by Sugoiiiii** [comment]
py runs but returns 

Traceback (most recent call last):
  File "main.py", line 197, in <module>
    main()
  File "main.py", line 192, in main
    batchDecrypt(srcDir=srcDir, xxteaKey=xxtea_key, sign=sign)
  File "main.py", line 144, in batchDecrypt
    decData = decrypt(filePath, xxteaKey, sign)  # decrypt core
  File "main.py", line 124, in decrypt
    dec_data = xxtea.decrypt(data=data[len(sign):], key=key[:16], padding=False, rounds=0)
ValueError: Data length must be a multiple of 4 bytes and must not be less than 8 bytes

**Comment by Mas0nShi** [comment]
> 

give me `apk` file if it's convenient for you, i will look at it later. (

**Comment by Sugoiiiii** [comment]
Does xxtea need to specify the version?

**Comment by Mas0nShi** [comment]
No, it's standard algorithm.

**Comment by Mas0nShi** [comment]
I don't know this app is modify default encryption or not, so there's nothing I can do.

**Comment by Sugoiiiii** [comment]
Is this a decryption fail?
![image](https://user-images.githubusercontent.com/93562135/167283027-ace81dd4-82c2-40d9-b821-e458d17e00b1.png)

**Comment by Sugoiiiii** [comment]
Is this decryption fail?

![image](https://user-images.githubusercontent.com/93562135/167283207-9689f07c-1769-4582-b93f-3cb2d2b0290c.png)

**Comment by Mas0nShi** [comment]
no, it's looks like luajit.
